### ISSUE TITLE
feat(map): CandidateLegend

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/bkk-election-2022#1]
![image](https://user-images.githubusercontent.com/8860448/164896768-6e8d7127-85ec-4451-9399-26647c7f2dc7.png)

## Context
- `presetContext` from `context/preset`

## Behaviour
Show unique candidates of `TOP_CANDIDATE_DISPLAY` (/constants) in each district (A set of 3 candidates with highest count in each district)

**Comment by Th1nkK1D** [comment]
มีเรื่องฝากแก้

1. Component `CandidateLegend` ตกตัว d ด้านหลังไป
2. typography style ของ children ยังไม่ถูกนะ
3. คิดว่า logic ที่แสดง candidate คนไหนบ้างก็ยังไม่ถูก แต่ตรงนี้ละไว้ก่อน เราลืมคิดไปว่ามันอาจจะไม่เหมือนกันใน visualization แต่ละประเภท กำลังคุยกับเต้อยู่ เดี๋ยวมีไรจะมาอัพเดตฮะ
4. แนะนำให้ตั้งชื่อ `Props` ให้มันชัดเจนไปเลยว่าเป็น props ของอะไร เช่่น `CandidateLegendProps` เพราะบางครั้งเราก็เขียนมากกว่าหนึ่ง component ใน JSX ไฟล์เดียว

นอกจากนั้นจัดว่ายอดเยี่ยมจัด งานไว

**Comment by napatswift** [comment]
typography style ของ children ผมคิดว่าจะให้คนที่ใส่ children ปรับเองอะคับ แต่ตามที่บอก ให้ใส่ใน component ไปเลยใช่ไหมครับ

**Comment by Th1nkK1D** [comment]
> typography style ของ children ผมคิดว่าจะให้คนที่ใส่ children ปรับเองอะคับ แต่ตามที่บอก ให้ใส่ใน component ไปเลยใช่ไหมครับ

อ๋า ถ้าดูจาก design แล้วมันใช้แบบเดียวกัน เรากำหนดไปเลยก็ได้ฮะ

**Comment by Th1nkK1D** [comment]
มาเคลียส่วน logic แสดง candidate ที่ตอนนั้นติดกันไว้ฮะ ฝากทำ props ขึ้นมาตัวนึงชื่อ `topCandidatePerDistrict` : `number` ละให้แสดงผู้สมัครทั้งหมดที่ติดอันดับสูงสุดตามที่กำหนดไว้ใน `topCandidatePerDistrict` (ไม่ต้องใช้ TOP_CANDIDATE_DISPLAY แล้วเพราะ vis แต่ละอันดันไม่เท่ากัน ตอนนี้โยนเลขไรก็ได้ใส่มาก่อน เดี๋ยวเคลียพวก constant ตามไปให้)

ยกตัวอย่างเช่น ถ้ามี candidate `1,2,3,4` แล้วมีสองเขตซึ่งลำดับคะแนนโหวตเป็น `1,2,3,4` และ `1,3,4,2` ถ้ากำหนด `topCandidatePerDistrict = 2` เราจะพบว่า top 2 ของแต่ละเขตคือ `1,2` กับ `1,3` เพราะงั้นให้โชว `1,2,3`

**Comment by napatswift** [comment]
สงสัยครับ ถ้าแต่ละเขตมี top 2 ไม่เหมือนกันก็จะเอามารวมกันทุกเขตเลยไหมครับ (`((1,2), (3,2), (2,4)) => (1,2,3,4)`)

**Comment by Th1nkK1D** [comment]
> สงสัยครับ ถ้าแต่ละเขตมี top 2 ไม่เหมือนกันก็จะเอามารวมกันทุกเขตเลยไหมครับ (`((1,2), (3,2), (2,4)) => (1,2,3,4)`)

ถูกต้องแล้ว คุยกับเต้ว่าโชวมันหมดเลย ถ้า overflow ให้ scroll ข้างเอา

**Comment by Th1nkK1D** [comment]
ซอรี่ ลืมเขียน behavior ของ mobile ให้ซ่อน `children` ไว้ แทนที่ด้วยปุ่มวิธีอ่าน พอกดปุ่มวิธีอ่านแล้วค่อยเปิด modal (ใช้ `<Modal />` #11 ) ที่มี `children` อยู่ข้างใน
![image](https://user-images.githubusercontent.com/8860448/166324257-29dfc509-bbdc-4e75-b168-46cbcea70fb2.png)
![image](https://user-images.githubusercontent.com/8860448/166324432-988b4445-8bf3-48e6-8610-61d9b801bdd2.png)
