### ISSUE TITLE
feat(map): DistrictTooltip

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/bkk-election-2022#2]
![image](https://user-images.githubusercontent.com/8860448/164903795-e4fafaca-f541-416e-88c2-7382b44bbbd3.png)

## Context
- `presetContext` from `context/preset`

## Behavior
- Don't care about show/hide logic
- Display amount = `TOP_CANDIDATE_DISPLAY`
- Clicking behavior is under discussion with the designer, ignore it for now.

**Comment by Th1nkK1D** [comment]
@Bariyard Sorry krub. Because the component content depends on the hover district, So I this component requires props (and context might not be needed).

**Comment by Th1nkK1D** [comment]
@Bariyard Sorry krub. We will update this component a bit according to the design changes. We will make it more generalized so the #5 can use it as well.

1. The design is changed a bit (No more eligible voters)

![image](https://user-images.githubusercontent.com/8860448/166206036-af1769d9-33bc-4c77-9681-4f50d43300cc.png)

2. The component should depend on props instead of context. My proposed props:
- district: `District`
- topCandidateDisplay: `number` to define how many top candidate vote percentage will be show

3. No need to show clicking text right now. It's not our priority yet.

**Comment by Bariyard** [comment]
completed <3
