### ISSUE TITLE
feat(map): GridRatioVisualization

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/bkk-election-2022#3]
![image](https://user-images.githubusercontent.com/8860448/164898622-dac27008-3c7a-41b9-945e-0a335305ab1c.png)

## Depends on
- #1 
- #2

## Context
- `presetContext` from `context/preset`

## Behavior
- District area is relative to `district.eligiblePopulation` 
- Show `TOP_CANDIDATE_DISPLAY` with color, the rest is `DEFAULT_CANDUDATE_COLOR`  (both defined in `/constants/candidate`) 
- Show #2 when hovering on each district

**Comment by Bariyard** [comment]
completed <3
