### ISSUE TITLE
feat(map): MapWinnerVisualization

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/bkk-election-2022#4]
![image](https://user-images.githubusercontent.com/8860448/164908978-edd5c37b-c397-488c-8152-aba657381e2b.png)

## Depends on
- #1 
- #2

## Context
- `presetContext` from `context/preset`

## Behavior
- District area is relative to `district.eligiblePopulation` 
- Show only the winning candidate's color in each district
- Show #2 when hovering over each district

**Comment by Bariyard** [comment]
completed <3
