### ISSUE TITLE
feat(map): ListRatioVisualization

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/bkk-election-2022#5]
![image](https://user-images.githubusercontent.com/8860448/164909730-879dc4db-1207-4fba-873f-ac5d4816b755.png)

## Depends on
- #1 

## Context
- `presetContext` from `context/preset`

## Behavior
- Click on the table header to sort with that value. Default is a district name
- The tooltip is under discussion with designer

**Comment by napatswift** [comment]
`นับคะแนนแล้ว` นี่คิดโดยใช้`ผลคะแนนรวม`กับ`ผู้มีสิทธิ์`ไหมครับ

**Comment by Th1nkK1D** [comment]
> `นับคะแนนแล้ว` นี่คิดโดยใช้`ผลคะแนนรวม`กับ`ผู้มีสิทธิ์`ไหมครับ

เราเพิ่ม field progress ให้ละ เพราะผู้มิสิทธ์ - คะแนนรวม มันคือคะแนนรวม แต่ว่านับคะแนนแล้วต้องเป็นของคะแนน live ว่านับไปแค่ไหนแล้ว

```ts
export interface Voting {
  eligiblePopulation: number;
  totalVotes: number;
  progress?: number; // <- added!
  result: Result[];
}
```

ข้อมูลที่ไม่ใช่  live ก็จะไม่มี `progress` ก็ซ่อนคอลัมนี้ไปเลย

**Comment by taepras** [comment]
ไม่แน่ใจเกี่ยวกับ issue นี้โดยตรงมั้ย แต่ถ้าใช่เดี๋ยวฝากปรับ behavior ของการ sort ตารางนิดนึงได้มั้ยครับ คือพอกด header ของ column ไหน ครั้งแรกให้ sort high-low กดอีกทีให้กลับด้านของการ sort toggle สลับไปมา (behavior แบบเดียวกับตารางในหน้านี้เลย https://www.nytimes.com/interactive/2021/world/covid-cases.html)

(ไม่แน่ใจว่าสามารถมี default แยก column ได้มั้ย แต่ถ้าได้ จริงๆ อยากได้อะไรแนวๆ ถ้าเรียงชื่อกดครั้งแรกเป็น ก-ฮ แต่ถ้าเรียงคะแนนเป็นแบบมากไปน้อย เรียงจำนวนผู้มีสิทธิ์ฯ จากมากไปน้อย เรียงเลขผู้สมัครน้อยไปมาก อะไรงี้ฮะ 🤔 ถ้าไม่ได้ไม่เป็นไร เรียง low-high หมดเลยก็ได้)

**Comment by napatswift** [comment]
ได้เลยครับ เดี๋ยวทำเรียงจากน้อยไปมากด้วยครับ (รวมตาราง overview #6 ด้วย)

เพิ่มเติมครับ มี prototype ที่ไม่มี column `นับคะแนนแล้ว` ไหมครับ

**Comment by taepras** [comment]
ไม่ได้ทำไว้ฮะ แต่แค่ยืด column ที่เหลือออกไปชิดขวาได้เลย 
(desktop ยืดกราฟให้สุดขอบ / mobile ดันจำนวนคนเลือกมาชิดขวา)

**Comment by Th1nkK1D** [comment]
@napatswift ตามดีไซน์มันไม่มี % ตรงผู้มีสิทธิเลือกตั้งปะนะ แล้วตามตรงตอนนี้งงว่ามันคือ % ของอะไร? เทียบกับผู้มีสิททั้งหรุงเทพ หรือเทียบกับประชากรของเขตนั้น

**Comment by napatswift** [comment]
- ใน mobile มันมีครับ เแอบถาม @taepras มาละ สรุปว่าใน destop ก็มี
- ผู้มีสิทธิ์ในเขตกับทั้ง กทม ครับ

<img width="408" alt="Screen Shot 2565-05-02 at 16 22 37" src="https://user-images.githubusercontent.com/26627006/166212931-c5f40c4c-b47a-4558-9759-64413fede98f.png">
