### ISSUE TITLE
feat(map): CandidateOverviewList

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/bkk-election-2022#6]
![image](https://user-images.githubusercontent.com/8860448/164909981-82d5b577-76d8-4130-91bd-bd13bfd603e7.png)

## Context
- `presetContext` from `context/preset`

## Behavior
- First `TOP_CANDIDATE_DISPLAY` will be bigger which includes the candidate image
- Click on the table header to sort with that value. Default is count.

**Comment by Th1nkK1D** [comment]
1. ตรงพวก header เราใช้ของซ้ำๆ กันอะ มองว่าสามารถยกตรงนี้ไปเป็น component ใหม่ได้ บางส่วนที่ไม่ซ้ำก็โยนใส่ prop เข้าไป
```tsx
// CandidateOverviewList: line 42
<span
  class="text-left flex-1 opacity-50 cursor-pointer"
  onClick={() => setSortType('NAME')}
>
  ผู้สมัคร [หมายเลข]
  {sortType === 'NAME' && '↓'}
</span>
```

2. อยากรู้ว่าทำไมถึงเลือกใช้ background-image นะ เพราะโดยทั่วไปแล้วถ้าใช้ `<img />` ได้เหมือนกัน แนะนำให้ใช้อันนี้ดีกว่า มันมี accessibility ที่ดีกว่า พวก screen reader จะรู้ว่านี่คือภาพ และมี alt อธิบายภาพ
```tsx
// RowItem.tsx: line: 55
<div
 style={{ backgroundImage: `url('${STRIP_GIF_PATH}')` }}
 class="opacity-20 w-full h-auto left-0 top-0"
/>
```

**Comment by Th1nkK1D** [comment]
ฝากนิดเดียว
1. เอาพวก import ที่ไม่ใช้ออก
2. อยากให้ชื่อ Component ที่ Import มาเหมือนกับต้นฉบับ ยาวก็ไม่เป็นไร จะได้เสิร์ชหาได้ว่าใช้ที่ไหนบ้าง
```ts
// apps/map/src/components/candidateOverviewList/CandidateOverviewList.tsx : line5
import RowItem, { PARTY_UNDEFINED_STRING } from './CandidateOverviewListRowItem';
```
3. อันนี้สงสัยเฉยๆ เห็นมีใช้การ format % สองแบบ `toFixed + '%'` กับ `toLocaleString` อยากรู้ว่าทำไมถึงใช้ไม่เหมือนกันนะ

นอกจากนั้นงานดีละฮะ โคตรถือว่าคุณภาพดีมาก ถ้าแก้สองอันแรกปิด issue ได้เลย

**Comment by napatswift** [comment]
will this component be used in this pop-up component?

![image](https://user-images.githubusercontent.com/26627006/166240885-baf72f46-d17a-41a3-a30f-6d7bdee8a562.png)

should i make it more general so this can be used in it too krub? or ignore it for now.

**Comment by taepras** [comment]
> will this component be used in this pop-up component?
> 
> ![image](https://user-images.githubusercontent.com/26627006/166240885-baf72f46-d17a-41a3-a30f-6d7bdee8a562.png)
> 
> should i make it more general so this can be used in it too krub? or ignore it for now.

ไม่แน่ใจว่าหมายถึงยังไง ขยายความเพิ่มนิดได้มั้ยฮะ

(ถ้าสงสัยเรื่องตัว pop up มีใช้ที่อื่นครับ โดยเฉพาะกับ mobile แต่ใช้แค่กรอบกับปุ่มปิด)

**Comment by napatswift** [comment]
สงสัยว่า candidateOverviewList จะไปใช้ใน pop up รายเขต (ในรูป) ด้วยรึเปล่าครับ เพราะมันต่างกันแค่ไม่ต้องมีบาร์ที่ใหญ่กว่าบาร์อื่น กับขอบบาร์ไม่มน

**Comment by Th1nkK1D** [comment]
> สงสัยว่า candidateOverviewList จะไปใช้ใน pop up รายเขต (ในรูป) ด้วยรึเปล่าครับ เพราะมันต่างกันแค่ไม่ต้องมีบาร์ที่ใหญ่กว่าบาร์อื่น กับขอบบาร์ไม่มน

เป็น point ที่ดีมากครับผมมมม ถึงจุดนึงจะแนะนำให้ refactor ให้มัน generalise มากขึ้น หรือจริงๆ แยกออกมาอีก component ที่รับ props ก็ได้แล้วตัว `CandidateOverviewList` เป็นคนดึง context ส่งไปให้ ส่วน popup ก็ส่งเข้าไปของมัน แต่ว่าเนื่องจากว่า popup ยังไม่ได้อยู่ใน priority แรก และไม่มั่นใจว่ capacity team จะทำทันไปถึงจุดไหน เลยยังไม่ได้พูดถึงจุดนี้ และยังไม่ได้สร้าง issue ของ pop up ครับ เพราะถ้าทำไปไม่ถึงมันก็คือทำฟรี แนวคิดเรื่องอย่าเพิ่งกังวลของที่ยังไม่จำเป็นต้องทำมากเกินไปชื่อ yagni ฮะ เผื่ออยากอ่านเพิ่ม https://www.martinfowler.com/bliki/Yagni.html

**Comment by taepras** [comment]
อ๋อ เข้าใจแล้ว จริงๆ design ไว้ให้มัน reuse กันได้อยู่ครับ ถ้าเป็นไปได้ก็ใช้แชร์กันได้เลย

**Comment by napatswift** [comment]
ขอบคุณคับ เห็นมันมีใน prototype เลยคิดว่าน่าจะต้องทำ แล้วก็ไม่ต้อง refactor เยอะในอนาคตถ้าทำตอนนี้ 555

**Comment by Th1nkK1D** [comment]
> ขอบคุณคับ เห็นมันมีใน prototype เลยคิดว่าน่าจะต้องทำ แล้วก็ไม่ต้อง refactor เยอะในอนาคตถ้าทำตอนนี้ 555

แต่ถ้าดูจากสปีดทีมตอนนี้ น่าจะทำทันแหละ ถ้าอยากปรับไรเตรียมไว้รอก็ได้เลย
