### ISSUE TITLE
feat(map): VisualizationToggle

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/bkk-election-2022#8]
![image](https://user-images.githubusercontent.com/8860448/165523598-fc558bba-9c87-43bb-833e-413ebb22e054.png)
**NOTE:** We won't implement "ผู้ชนะ (ที่กริด)" yet. Skip it for now.

## Props
- activeVisualization: `Visualization` enum (`models/visualization`)
- onChange: (visualization: `Visualization` enum) => void

## Behavior
- Show active state on visualization button that match `activeVisualization`
- When the button is clicked, call `onChange` with corresponded `Visualization` enum
    - Don't call if the active button is clicked

**Comment by taepras** [comment]
https://www.figma.com/file/IQZXEhnhfUXkHpJMJw3KQw
note for this issue: you can export svgs for the button thumbnails from here.
